services:
  db:
    restart: unless-stopped
    image: postgres:16
    volumes: ["./tmp/postgres:/var/lib/postgresql/data/"]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres.gudfmhvqzmnvywbwoiwk
      - POSTGRES_PASSWORD=ZzAw1@Kg58#
    ports:
      - mode: host
        target: 6543
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M

  django-crm:
    restart: unless-stopped
    build: ./app
    ports:
      - mode: ingress
        target: 8000
        # Uncomment the following line if you want to run it locally
        # published: 8000
    environment:
      - DB_HOST=aws-0-us-west-1.pooler.supabase.com
      - DEBUG=False
      - POSTGRES_USER=postgres.gudfmhvqzmnvywbwoiwk
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=ZzAw1@Kg58#
    # deploy:
    #   resources:
    #     reservations:
    #       memory: 2GB
    # volumes: [".:/code"]
    depends_on:
      - db
    # command: python manage.py runserver 0.0.0.0:8000
