# Generated by Django 5.1.4 on 2024-12-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='texto',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='capitulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='versiculo',
            field=models.TextField(default=''),
        ),
    ]
