# Generated by Django 5.1.4 on 2024-12-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0003_remove_mensagem_culto'),
    ]

    operations = [
        migrations.AddField(
            model_name='culto',
            name='imagem',
            field=models.ImageField(default='', upload_to='galeria'),
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
